# Generated by Django 4.0.3 on 2022-05-25 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_board_remove_question_category_delete_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='index',
        ),
    ]
