# Generated by Django 4.0.3 on 2022-05-25 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_board_create_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='create_date',
        ),
        migrations.AddField(
            model_name='board',
            name='index_num',
            field=models.IntegerField(null=True),
        ),
    ]
