# Generated by Django 4.0.3 on 2022-05-25 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0011_answer_modify_date_question_modify_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='modify_date',
        ),
        migrations.RemoveField(
            model_name='question',
            name='modify_date',
        ),
    ]
