# Generated by Django 4.0.3 on 2022-05-28 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0015_board_question_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='photo',
            field=models.ImageField(null=True, upload_to='media/%Y/%m/%d'),
        ),
    ]
