# Generated by Django 4.0.3 on 2022-05-29 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0016_question_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='uploadedFile',
            field=models.FileField(blank=True, null=True, upload_to='media/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='question',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/%Y/%m/%d'),
        ),
    ]
