# Generated by Django 4.0.3 on 2022-05-29 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0017_question_uploadedfile_alter_question_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='uploadedFile',
        ),
    ]
