# Generated by Django 4.0.3 on 2022-05-29 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0018_remove_question_uploadedfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media/%Y/%m/%d'),
        ),
    ]
