# Generated by Django 4.0.3 on 2022-05-31 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0020_remove_question_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=30, unique=True)),
                ('description1', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='board2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='board_question', to='board.board2'),
        ),
    ]
