# Generated by Django 4.0.3 on 2022-05-31 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0021_board2_question_board2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='board2',
        ),
        migrations.AddField(
            model_name='board',
            name='board2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='board_question', to='board.board2'),
        ),
    ]
